// ===== CONFIG =====
const WA='919790524200';
const CARATS=[1,2,3,5], $=s=>document.querySelector(s);
const ls={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const e=s=>String(s).replace(/[&<>"']/g,c=>'&#'+c.charCodeAt(0)+';'),inr=n=>'₹'+n.toLocaleString('en-IN');
const price=(p,c)=>Math.round(p.ppc*c*(1+.04*(c-1))); // larger stones carry a small per-carat premium
let P=[],cart=ls.get('cart',[]),ME=null,ORD=[],WL=ls.get('wl',[]);const user=()=>ME,find=id=>P.find(p=>p.id==id);
const api=async(u,b)=>{const r=await fetch(u,{method:b?'POST':'GET',headers:{'Content-Type':'application/json'},body:b?JSON.stringify(b):undefined}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Something went wrong');return j};
const PART={precious:['Precious stones','The four classical gems: diamond, ruby, emerald and sapphire. Rare, hard and long-lasting.'],
semi:['Semi-precious stones','Beautiful, more affordable stones with a wide colour range, ideal for daily jewellery.'],
navratna:['Navratna: the nine gems','The nine planetary gems of Vedic tradition, sold individually so you can pick the one you need.']};
async function init(){const r=await api('/api/products');P=r.map(p=>({id:p.id,name:p.name,cat:p.category,color:p.color,ppc:p.price_per_carat,desc:p.description}));
try{ME=(await api('/api/me')).user}catch{}
addEventListener('hashchange',go);go()}
init().catch(()=>$('#app').innerHTML='<p class="err">Cannot reach the server. Start it with: npm start</p>');
function nav(){const n=cart.reduce((s,i)=>s+i.q,0),u=user(),L=c=>P.filter(p=>p.cat==c).map(p=>`<a href="#stone/${p.id}">${e(p.name)}</a>`).join('');
$('#util').innerHTML=`<form onsubmit="event.preventDefault();location.hash='search/'+encodeURIComponent(this.q.value)"><input name="q" placeholder="Search stones" aria-label="Search stones"></form><a href="#wishlist">Wishlist (${WL.length})</a><a href="${u?'#track':'#login'}">${u?'Hi, '+e(u.name.split(' ')[0]):'Account'}</a>${u?'<a href="#home" onclick="logout(event)">Log out</a>':'<a href="#signup">Sign up</a>'}<a href="#cart">Cart (${n})</a>`;
$('#nav').innerHTML=`<a href="#home">Home</a><div class="mm"><a href="#shop">Gemstones &#9662;</a><div class="drop"><div><b>Navratna</b>${L('navratna')}</div><div><b>Precious stones</b>${L('precious')}</div><div><b>Semi-precious stones</b>${L('semi')}</div><div><b>Collections</b><a href="#shop/navratna">All Navratna</a><a href="#shop/precious">All precious</a><a href="#shop/semi">All semi-precious</a><a href="#shop">View all</a></div></div></div><div class="mm"><a href="#birth/${MON[new Date().getMonth()][0]}">Birthstones &#9662;</a><div class="drop"><div><b>By month</b>${MON.slice(0,6).map(m=>`<a href="#birth/${m[0]}">${m[1]}</a>`).join('')}</div><div><b>&nbsp;</b>${MON.slice(6).map(m=>`<a href="#birth/${m[0]}">${m[1]}</a>`).join('')}</div></div></div><a href="#track">My orders</a><a href="#contact">Contact us</a>`}
async function go(){$('#yr').textContent=new Date().getFullYear();const[h,a]=(location.hash.slice(1)||'home').split('/');
if((h=='track'||h=='success')&&ME){try{ORD=await api('/api/orders')}catch{}}
$('#app').innerHTML=(V[h]||V.home)(a);nav();scrollTo(0,0)}
const gem=(p,x='')=>`<svg class="gem ${x}" viewBox="0 0 100 100" role="img" aria-label="${e(p.name)}"><polygon points="25,10 75,10 98,38 50,94 2,38" fill="${p.color}"/><polygon points="25,10 50,38 2,38" fill="#fff" opacity=".28"/><polygon points="25,10 75,10 50,38" fill="#fff" opacity=".5"/><polygon points="75,10 98,38 50,38" fill="#fff" opacity=".12"/><polygon points="2,38 50,38 50,94" fill="#000" opacity=".18"/><polygon points="98,38 50,38 50,94" fill="#000" opacity=".32"/><polygon points="25,10 75,10 98,38 50,94 2,38" fill="none" stroke="#fff" stroke-opacity=".55"/></svg>`;
let SQ='',SS='',BM;
const MON=[['january','January',7],['february','February',5],['march','March',20],['april','April',1],['may','May',3],['june','June',12],['july','July',2],['august','August',21],['september','September',4],['october','October',22],['november','November',8],['december','December',10]];
const V={
home(){const r=find(2),em=find(3),n=P.filter(p=>p.cat=='navratna'),m=['January Garnet','February Amethyst','March Aquamarine','April Diamond','May Emerald','June Pearl','July Ruby','August Peridot','September Sapphire','October Opal','November Topaz','December Turquoise'];
return`<div class="issue"><span>Issue No. 1</span><span>${new Date().toLocaleDateString('en-IN',{month:'long',year:'numeric'})}</span><span>Lustre Lapidist, India</span></div>
<div class="title">The Lustre Review</div>
<section class="lead"><div><span class="tag">COVER STORY</span><h1 style="font-size:clamp(2.4rem,6vw,4.5rem)">Colour that was a mountain once.</h1><p class="drop">Every gemstone starts as a mineral grown slowly underground. Cut by a lapidist, it becomes the ruby on a bride's hand or the amethyst on a child's first ring. At Lustre Lapidist we pick stones for colour, clarity and honest weight, then price them by the carat so you always know what you pay for.</p>
<div class="quote">A carat is only 0.2 grams, yet it can change the whole ring.</div><a class="btn" href="#shop">Shop all gemstones</a> <a class="btn alt" href="#contact">Ask a gemologist</a></div>
<aside class="side"><div style="display:grid;place-items:center">${gem(r,'xl')}</div><h3>Gem of the issue: Ruby</h3><p>${e(r.desc)} From ${inr(price(r,1))} for one carat.</p><a href="#shop/precious">See rubies</a></aside></section>
<section class="spread"><article><span class="tag">GUIDE</span><h2>Precious or semi-precious?</h2><p>Precious means diamond, ruby, emerald and sapphire. Semi-precious covers every other stone, and many are lovely, hard and far cheaper.</p><a href="#shop">Compare both</a></article>
<article><span class="tag">TRADITION</span><h2>The Navratna nine</h2><p>Nine stones, nine planets. Each one is sold on its own here, so you can buy the single gem your astrologer advises.</p><a href="#shop/navratna">Meet the nine</a></article>
<article><span class="tag">BUYING TIPS</span><h2>How to read a price</h2><p>Look at weight, colour and clarity together. Larger stones cost more per carat because fine large crystals are rare.</p><a href="#shop">See carat prices</a></article></section>
<section class="lead"><div><span class="tag">COLLECTION</span><h2>The nine gems</h2><div class="strip">${n.map(p=>`<a href="#shop/navratna">${gem(p)}<div>${e(p.name)}</div></a>`).join('')}</div></div>
<aside class="side"><h3>Birthstone by month</h3><table class="bs">${m.map(x=>`<tr><td>${x.split(' ')[0]}</td><td>${x.split(' ')[1]}</td></tr>`).join('')}</table></aside></section>
<section class="spread">${Object.entries(PART).map(([k,[t,d]])=>`<article><span class="tag">SHOP</span><h2>${t}</h2><p>${d}</p><a href="#shop/${k}">View collection</a></article>`).join('')}</section>
<section class="trust"><div><h3>Priced by the carat</h3><p>See every size and price before you buy.</p></div><div><h3>Insured delivery</h3><p>Tracked from our hands to yours.</p></div><div><h3>Secure payment</h3><p>UPI, cards and net banking via Razorpay.</p></div><div><h3>Talk to a person</h3><p>Call or WhatsApp +91 97905 24200.</p></div></section>
<h2>Questions, answered</h2><details><summary>What is a carat?</summary><p>A carat is a unit of weight equal to 0.2 grams. Heavier stones cost more, and large fine stones cost more per carat.</p></details><details><summary>How do I pay?</summary><p>Checkout accepts UPI, debit and credit cards and net banking.</p></details><details><summary>How do I track my order?</summary><p>Log in and open My orders to see each stage from confirmed to delivered.</p></details><details><summary>Can I ask before I buy?</summary><p>Yes. Use the chat button, WhatsApp or the contact page.</p></details>`},
shop(a){return`<h1 style="font-size:3rem">Shop gemstones</h1><div class="tools"><input id="sq" type="search" placeholder="Search stones, e.g. ruby" oninput="drawShop()" value="${e(SQ)}"><select id="ss" onchange="drawShop()"><option value="">Sort: featured</option><option value="lo" ${SS=='lo'?'selected':''}>Price: low to high</option><option value="hi" ${SS=='hi'?'selected':''}>Price: high to low</option></select></div><div class="tabs"><a class="btn alt" href="#shop">All</a>${Object.entries(PART).map(([k,[t]])=>`<a class="btn alt" href="#shop/${k}">${t}</a>`).join('')}</div><div id="shopbody">${shopBody(a)}</div>`},
cart(){if(!cart.length)return`<h1>Your cart</h1><p>Your cart is empty.</p><a class="btn" href="#shop">Shop gemstones</a>`;
return`<h1>Your cart</h1>${cart.map((i,x)=>{const p=find(i.id);return`<div class="row">${gem(p)}<div class="grow"><b>${e(p.name)}</b><br>${i.c} carat &times; ${inr(price(p,i.c))}</div><button class="btn alt" onclick="qty(${x},-1)" aria-label="Less">-</button>${i.q}<button class="btn alt" onclick="qty(${x},1)" aria-label="More">+</button><b>${inr(price(p,i.c)*i.q)}</b></div>`}).join('')}<h2 style="margin-top:20px">Total: ${inr(total())}</h2><a class="btn" href="#checkout">Proceed to checkout</a>`},
checkout(){if(!user()){sessionStorage.next='checkout';return V.login()}if(!cart.length)return V.cart();
return`<h1>Delivery address</h1><form onsubmit="pay(event)"><input name="name" placeholder="Full name" required value="${e(user().name)}"><input name="phone" placeholder="Mobile number" pattern="[0-9]{10}" required><textarea name="line" placeholder="House, street, area" required></textarea><input name="city" placeholder="City" required><input name="state" placeholder="State" required><input name="pin" placeholder="PIN code" pattern="[0-9]{6}" required><b>Amount: ${inr(total())}</b><button class="btn">Pay securely</button></form>`},
success(id){const o=ORD.find(o=>o.id==id);if(!o)return V.home();return`<h1>Order placed</h1><p>Thank you, ${e(o.addr.name)}. Your order <b>${o.id}</b> is confirmed. Payment ID: ${e(o.pay)}.</p><h3>Delivering to</h3><p>${e(o.addr.line)}, ${e(o.addr.city)}, ${e(o.addr.state)} - ${e(o.addr.pin)}<br>Phone: ${e(o.addr.phone)}</p><a class="btn" href="#track">Track order</a> <a class="btn alt" target="_blank" rel="noopener" href="https://wa.me/${WA}?text=${encodeURIComponent('Hi, I placed order '+o.id+' ('+inr(o.total)+')')}">Confirm on WhatsApp</a>`},
track(){const u=user();if(!u){sessionStorage.next='track';return V.login()}const os=ORD;if(!os.length)return`<h1>My orders</h1><p>No orders yet.</p>`;
const S=['Confirmed','Packed','Shipped','Out for delivery','Delivered'];
return`<h1>My orders</h1>`+os.map(o=>{const st=S.indexOf(o.status);return`<div class="card" style="margin-bottom:16px"><b>${o.id}</b> &middot; ${inr(o.total)} &middot; ${new Date(o.t).toLocaleDateString('en-IN')}<div>${o.items.map(i=>e(i.name)+' '+i.c+'ct x'+i.q).join(', ')}</div><div class="steps">${S.map((s,i)=>`<span class="${i<=st?'on':''}">${s}</span>`).join('')}</div><small>Ship to: ${e(o.addr.line)}, ${e(o.addr.city)} - ${e(o.addr.pin)}</small></div>`}).join('')},
login(){return`<h1>Log in</h1><form onsubmit="login(event)"><input name="email" type="email" placeholder="Email" required><input name="pw" type="password" placeholder="Password" required><span class="err" id="msg"></span><button class="btn">Log in</button><a href="#signup">Create an account</a></form>`},
signup(){return`<h1>Create account</h1><form onsubmit="signup(event)"><input name="name" placeholder="Full name" required><input name="email" type="email" placeholder="Email" required><input name="pw" type="password" minlength="6" placeholder="Password (6+ characters)" required><span class="err" id="msg"></span><button class="btn">Sign up</button></form>`},
wishlist(){const l=WL.map(find).filter(Boolean);return`<h1>Your wishlist</h1>`+(l.length?l.map(p=>`<div class="row">${gem(p)}<div class="grow"><b>${e(p.name)}</b><br>From ${inr(price(p,1))} for 1 carat</div><a class="btn alt" href="#stone/${p.id}">View</a><button class="btn alt" onclick="toggleWL(${p.id});go()">Remove</button></div>`).join(''):'<p>You have not saved any stones yet. Tap the heart on a stone to save it.</p><a class="btn" href="#shop">Browse gemstones</a>')+'<p><small>Your wishlist is saved in this browser.</small></p>'},
search(a){const q=decodeURIComponent(a||'');return`<h1>Search</h1><div class="tools"><input id="sq2" type="search" placeholder="Stone, month or planet, e.g. ruby, October, Venus" value="${e(q)}" oninput="drawSearch()"></div><div id="sres">${searchBody(q)}</div>`},
stone(a){const p=find(a);if(!p)return V.shop();return`<p class="crumb"><a href="#home">Home</a> &gt; <a href="#shop/${p.cat}">${PART[p.cat][0]}</a> &gt; ${e(p.name)}</p><div class="mod" style="margin-top:20px">${gem(p,'xl')}<div><h1 style="font-size:2.6rem">${e(p.name)} ${wl(p.id,"in")}</h1><p>${e(p.desc)}</p><table class="bs">${CARATS.map(c=>`<tr><td>${c} carat</td><td>${inr(price(p,c))}</td><td><button class="btn alt" onclick="add(${p.id},${c})">Add to cart</button></td></tr>`).join('')}</table>${infoBlock(p.id)}<p><a class="btn green" target="_blank" rel="noopener" href="https://wa.me/${WA}?text=${encodeURIComponent('Hi, I am interested in '+p.name)}">Talk to expert</a></p></div></div>`},
birth(a){const m=MON.find(x=>x[0]==a)||MON[9],p=find(m[2]);BM=m;return`<div class="banner">${gem(p,'b1')}${gem(p,'b2')}<h1>${m[1]}</h1></div><p class="crumb"><a href="#home">Home</a> &gt; ${m[1]} Birthstone</p><h2>${m[1]} Birthstone (${e(p.name)})</h2><p style="max-width:70ch">${e(p.desc)} Choose a weight below. Larger stones are priced a little higher per carat.</p>${infoBlock(p.id)}<a class="btn green" target="_blank" rel="noopener" href="https://wa.me/${WA}?text=${encodeURIComponent('Hi, I need help choosing a '+p.name)}">Talk to expert</a> <button class="btn alt" onclick="$('#flt').classList.toggle('open')">Show filters</button>
<div id="flt" class="flt"><b>Weight</b>${CARATS.map(c=>`<label><input type="checkbox" value="${c}" checked onchange="drawB()"> ${c} ct</label>`).join('')}<label>Max price <input id="mx" type="number" min="0" placeholder="No limit" oninput="drawB()"></label></div>
<div class="tools" style="justify-content:flex-end"><select id="bs" onchange="drawB()" style="max-width:260px"><option value="wl">Weight: Lowest to highest</option><option value="wh">Weight: Highest to lowest</option><option value="pl">Price: Lowest to highest</option><option value="ph">Price: Highest to lowest</option></select></div><div class="grid" id="bgrid">${bGrid(p,CARATS)}</div>`},
policy(a){const T={shipping:['Shipping','We ship across India with insured, tracked delivery. Orders are packed after payment is confirmed. Delivery time depends on your location.'],refund:['Returns and refunds','State your return window, the condition stones must be returned in, and how refunds are paid. Refunds go back to the original payment method.'],terms:['Terms of use','By ordering you agree that product colours may vary slightly on screen, prices are in INR and stock is subject to availability.'],privacy:['Privacy policy','We collect your name, email, phone and delivery address only to process orders. Passwords are stored hashed. We do not sell your data. Payments are handled by Razorpay.']}[a]||['Policies','Choose a policy from the footer.'];return`<h1>${T[0]}</h1><p class="note">Sample text. Edit this page to match your business before launch.</p><p style="max-width:70ch">${T[1]}</p>`},
contact(){return`<h1>Contact Lustre Lapidist</h1><p>Call or WhatsApp: <a href="tel:+919790524200">+91 97905 24200</a></p><form onsubmit="msg(event)"><input name="name" placeholder="Your name" required><textarea name="m" rows="4" placeholder="Which stone are you looking for?" required></textarea><button class="btn">Send on WhatsApp</button></form>`}};
// ===== SHOP HELPERS =====
const card=p=>`<div class="card">${wl(p.id)}<button class="lnk" onclick="openP(${p.id})" aria-label="Details for ${e(p.name)}">${gem(p)}</button><h3><a href="#" onclick="openP(${p.id});return false">${e(p.name)}</a></h3><p>${e(p.desc)}</p><label>Weight<select id="c${p.id}" onchange="$('#p${p.id}').textContent=inr(price(find(${p.id}),+this.value))">${CARATS.map(x=>`<option value="${x}">${x} carat</option>`).join('')}</select></label><div class="price" id="p${p.id}">${inr(price(p,1))}</div><button class="btn" onclick="add(${p.id},+$('#c${p.id}').value)">Add to cart</button></div>`;
function shopBody(a){const cats=PART[a]?[a]:Object.keys(PART),q=SQ.toLowerCase();let any=0;const out=cats.map(c=>{const l=P.filter(p=>p.cat==c&&(p.name+' '+p.desc).toLowerCase().includes(q));if(SS)l.sort((x,y)=>SS=='lo'?x.ppc-y.ppc:y.ppc-x.ppc);if(!l.length)return'';any=1;return`<section class="part"><h2>${PART[c][0]}</h2><p>${PART[c][1]}</p><div class="grid">${l.map(card).join('')}</div></section>`}).join('');return any?out:'<p>No stones match your search. Try another name.</p>'}
function drawShop(){SQ=$('#sq').value;SS=$('#ss').value;$('#shopbody').innerHTML=shopBody(location.hash.split('/')[1])}
function openP(id){const p=find(id);dlg.innerHTML=`<button class="x" onclick="dlg.close()" aria-label="Close">&times;</button><div class="mod">${gem(p,'xl')}<div><h2>${e(p.name)}</h2><p>${e(p.desc)}</p><table class="bs">${CARATS.map(c=>`<tr><td>${c} carat</td><td>${inr(price(p,c))}</td><td><button class="btn alt" onclick="add(${id},${c})">Add to cart</button></td></tr>`).join('')}</table><p><a class="btn" target="_blank" rel="noopener" href="https://wa.me/${WA}?text=${encodeURIComponent('Hi, I am interested in '+p.name)}">Ask about this stone</a></p></div></div>`;dlg.showModal()}
const bGrid=(p,l)=>l.length?l.map(c=>`<div class="card" style="align-items:center;text-align:center">${gem(p).replace('class="gem ','style="width:'+(50+c*14)+'px;height:'+(50+c*14)+'px" class="gem ')}<h3>${e(p.name)}</h3><div>${c} carat</div><div class="price">${inr(price(p,c))}</div><button class="btn" onclick="add(${p.id},${c})">Add to cart</button></div>`).join(''):'<p>No sizes match these filters.</p>';
function drawB(){const p=find(BM[2]),ch=[...document.querySelectorAll('#flt input[type=checkbox]:checked')].map(x=>+x.value),mx=+$('#mx').value||1e12,so=$('#bs').value;
const l=CARATS.filter(c=>ch.includes(c)&&price(p,c)<=mx).sort((a,b)=>so=='wl'?a-b:so=='wh'?b-a:so=='pl'?price(p,a)-price(p,b):price(p,b)-price(p,a));$('#bgrid').innerHTML=bGrid(p,l)}
const wl=(id,c='')=>`<button class="heart ${c}" data-w="${id}" onclick="toggleWL(${id})" aria-label="Save to wishlist">${WL.includes(id)?'&#9829;':'&#9825;'}</button>`;
function toggleWL(id){WL=WL.includes(id)?WL.filter(x=>x!=id):[...WL,id];ls.set('wl',WL);document.querySelectorAll('[data-w="'+id+'"]').forEach(b=>b.innerHTML=WL.includes(id)?'&#9829;':'&#9825;');nav()}
const infoBlock=id=>{const i=INFO[id];return i?`<table class="bs"><tr><td>Origin</td><td>${i[0]}</td></tr><tr><td>Hardness (Mohs)</td><td>${i[1]}</td></tr><tr><td>Tradition</td><td>${i[2]}</td></tr><tr><td>Care</td><td>${i[3]}</td></tr></table><p><small>Traditional beliefs are cultural, not medical or financial advice.</small></p>`:''};
function searchBody(q){q=q.trim().toLowerCase();if(!q)return'<p>Type a stone name, a month or a planet such as Venus.</p>';
const mo=MON.filter(m=>m[1].toLowerCase().startsWith(q)),l=P.filter(p=>(p.name+' '+p.desc+' '+(INFO[p.id]||[]).join(' ')).toLowerCase().includes(q));
return(mo.length?`<p>Birthstone pages: ${mo.map(m=>`<a href="#birth/${m[0]}">${m[1]}</a>`).join(', ')}</p>`:'')+(l.length?`<div class="grid">${l.map(card).join('')}</div>`:'<p>No stones found. Try another word or <a href="#contact">ask us</a>.</p>')}
function drawSearch(){$('#sres').innerHTML=searchBody($('#sq2').value)}
// ===== ACTIONS =====
const total=()=>cart.reduce((s,i)=>s+price(find(i.id),i.c)*i.q,0),save=()=>{ls.set('cart',cart);go()};
function add(id,c){const i=cart.find(i=>i.id==id&&i.c==c);i?i.q++:cart.push({id,c,q:1});ls.set('cart',cart);nav();toast(find(id).name+' added')}
function qty(x,d){cart[x].q+=d;if(cart[x].q<1)cart.splice(x,1);save()}
function toast(t){const d=document.createElement('div');d.textContent=t;d.style.cssText='position:fixed;left:50%;bottom:24px;transform:translateX(-50%);background:#1b1633;color:#fff;padding:10px 18px;border-radius:4px;z-index:9';document.body.append(d);setTimeout(()=>d.remove(),1600)}
const after=()=>{const n=sessionStorage.next||'home';delete sessionStorage.next;location.hash=n;go()};
async function signup(ev){ev.preventDefault();try{ME=(await api('/api/signup',Object.fromEntries(new FormData(ev.target)))).user;after()}catch(x){$('#msg').textContent=x.message}}
async function login(ev){ev.preventDefault();try{ME=(await api('/api/login',Object.fromEntries(new FormData(ev.target)))).user;after()}catch(x){$('#msg').textContent=x.message}}
async function logout(ev){ev&&ev.preventDefault();await api('/api/logout',{});ME=null;ORD=[];location.hash='home';go();toast('You are logged out')}
function msg(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));open(`https://wa.me/${WA}?text=${encodeURIComponent('Hi, I am '+f.name+'. '+f.m)}`)}
async function pay(ev){ev.preventDefault();const btn=ev.target.querySelector('button');btn.disabled=true;const addr=Object.fromEntries(new FormData(ev.target));
try{const o=await api('/api/checkout',{items:cart.map(i=>({id:i.id,c:i.c,q:i.q})),addr});
const done=async p=>{await api('/api/verify',{orderId:o.orderId,paymentId:p&&p.razorpay_payment_id,signature:p&&p.razorpay_signature});cart=[];ls.set('cart',cart);location.hash='success/'+o.orderId};
if(o.demo){if(confirm('DEMO MODE (no Razorpay keys on the server). Simulate a successful payment of '+inr(o.total)+'?'))await done();else btn.disabled=false;return}
new Razorpay({key:o.rzp.key,amount:o.rzp.amount,currency:'INR',order_id:o.rzp.orderId,name:'Lustre Lapidist',prefill:{name:addr.name,email:ME.email,contact:addr.phone},handler:r=>done(r).catch(x=>alert(x.message)),modal:{ondismiss:()=>btn.disabled=false}}).open()
}catch(x){alert(x.message);btn.disabled=false}}
// ===== CHATBOT =====
const say=(t,me)=>{const d=document.createElement('div');d.className=me?'me':'';d.innerHTML=t;log.append(d);log.scrollTop=1e9};
const BOT=[[/price|cost|rate/,'Prices are per carat and rise with weight. Each stone on the <a href="#shop">shop page</a> shows 1, 2, 3 and 5 carat prices.'],[/navratna|nine|planet/,'We sell all nine Navratna gems individually. See <a href="#shop/navratna">Navratna</a>.'],[/precious|diamond|ruby|emerald|sapphire/,'See our <a href="#shop/precious">precious stones</a>.'],[/semi|amethyst|citrine|topaz|garnet/,'See our <a href="#shop/semi">semi-precious stones</a>.'],[/deliver|ship|track/,'Orders ship across India. Log in and open <a href="#track">My orders</a> to track.'],[/pay|upi|card/,'We accept UPI, cards and net banking via Razorpay.'],[/call|phone|contact|number/,'Call or WhatsApp +91 97905 24200.']];
function ask(ev){ev.preventDefault();const t=q.value.trim();if(!t)return;say(e(t),1);q.value='';const m=BOT.find(b=>b[0].test(t.toLowerCase()));
say(m?m[1]:`I am not sure. <a target="_blank" rel="noopener" href="https://wa.me/${WA}?text=${encodeURIComponent(t)}">Continue this chat on WhatsApp</a>`)}
